### ISSUE TITLE
Discovery: local development with MFE plugin

### ISSUE THREAD

**Issue by rgraber** [edx/devenv-wg#2]
-     Determine if the current MFE plugin is sufficient for local development or, if not, what it will require to be so

-     If necessary, create issues with Tutor or 2u to address any gaps with the plugin

-     Document how to develop with MFEs locally for 2u engineers

**Comment by connorhaugh** [comment]
work thus far: 
I have: using https://github.com/overhangio/tutor-mfe#mfe-development I have been able to run a single MFE (learning) from the master fork. Code changes, like devstack, automatically are picked up which is nice-- I see no change in the speed those changes are picked up compared to learning mfe. 

What we need scripts to do:
-one script to run the three commands required to start developing one or **multiple mfes** for each MFE
- think about having the mfes (presently in config root/volume/app/)live adjacent to services, like devstack. Maybe scriopt creates a symlink?
- I don't know how to run multiple MFEs at the same time localy, and what processes would be required.

Is this: "sufficient for local development"? I would say for the wider 2u audience, definitely not until we have a more central plan on how we want tutor to "feel" for devs.

**Comment by connorhaugh** [comment]
I have since been able to run several MFEs locally in development mode (Learning, Course-authoring*, account), all using the above document. Just running the same process twice for the MFEs you care about works effectively.
 I think, however, there are some needs prescribed by this new workflow. 

1. We need to have a way to pull in all 2u-relevant MFEs into a (folder-of-repos) at $(tutor config printroot)/volumes/app/  so devs have one place to look for the relevant code, similar to how things function with Devstack. I'm not exactly sure how we want that to be but we will talk about that today, hopefully. Services might require more configuration, but MFEs are pretty quick to build. 

Also want to note that MFE build times in deployment, based on this conversation, might not be the same as development. https://discuss.openedx.org/t/microfrontends-a-retrospective/6486
